### ISSUE TITLE
Awesome Work! - but I have a question :) 

### ISSUE THREAD

**Issue by mauriciobergallo** [artilleryio/report-viewer#1]
Hey mate! first of all, thank you for your amazing work on this plugin.

I'm facing an "issue" maybe. I tried this plugin with my local version of artillery with no luck.

The info of artillery in my local machine is:

```
ARTILLERY DEV PREVIEW �
Please report bugs on https://github.com/artilleryio/artillery/issues

Modern performance testing toolkit

VERSION
  artillery/2.0.0-dev2 win32-x64 node-v12.16.3

USAGE
  $ artillery [COMMAND]

COMMANDS
  dino    here be dinosaurs
  help    display help for artillery
  report  generate a HTML report from a JSON log produced with artillery run
  run     run a test script
```

Maybe is something related with the lates version of Artillery ?

Thanks! 

PS: Sorry if I should reach you in a different way, but I didn't know how.

**Comment by cfryerdev** [comment]
Hey, could you provide more information? Not sure which plugin you are referring to. Happy to help wherever.  Feel free to reach out directly on our discord - [discord.gg/37vGhH3NMB](discord.gg/37vGhH3NMB)

**Comment by mauriciobergallo** [comment]
Hey! thanks for your feedback, yes, the plugin is: Report Viewer (https://github.com/artilleryio/report-viewer) maybe is not a plugin, just a tool, and this is the exported by Artillery.

Thanks in advance.


[20210413_1_basic.zip](https://github.com/artilleryio/report-viewer/files/6309748/20210413_1_basic.zip)

**Comment by cfryerdev** [comment]
Excellent, ill look into this today!

**Comment by mauriciobergallo** [comment]
Hey!

I've just tested the workaround that you've mentioned, but no look. 

This is the file that was exported.

Thanks in advanced!

[20210414_basic.zip](https://github.com/artilleryio/report-viewer/files/6314289/20210414_basic.zip)

**Comment by cfryerdev** [comment]
Closed, reportviewer.artillery.io should now support the v2 report object, let me know if you see anything odd :) Thank you!
